routes/admin.php
<?php


 Route::match(['put', 'patch'], '/activate-commision/{commission}','CommisionController@activate')->name('activate-commision');
Route::resource('commissions', 'CommisionController');

  Route::match(['put', 'patch'], '/activate/{campaign}','CampaignController@activate')->name('activate');

Route::resource('campaigns', 'CampaignController');
// https://packagist.org/packages/depsimon/laravel-wallet
Route::get('transactions', 'AdminController@transactions')->name('transactions');
Route::get('transactions/{id}', 'AdminController@ShowTransactions')->name('show.transactions');
Route::get('user-payaments/{id}', 'AdminController@manageUserPayaments')->name('user-payament');
Route::post('completUserPayaments', 'AdminController@CompletUserPayaments')->name('CompletUserPayaments');
Route::get('user-payaments', 'AdminController@userPayaments')->name('user-payaments');

Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
Route::get('shipping-orders', 'AdminController@shippings')->name('shippings');
Route::get('dealers-management', 'AdminController@members')->name('members');
Route::get('dealers.commissions', 'AdminController@dealersCommissions')->name('dealers.commissions');
Route::get('dealers_commissions_api', 'AdminController@dealers_commissions_api')->name('dealers_commissions_api');

Route::get('withdrawals_api', 'AdminController@withdrawals_api')->name('withdrawals_api');
Route::get('withdrawal-request-history', 'AdminController@withdrawals')->name('withdrawals');
Route::get('workspace', 'AdminController@workspace')->name('workspace');
Route::get('stocks-management', 'AdminController@stocks')->name('stocks');
Route::get('e-wallet', 'AdminController@credits')->name('credits');
Route::get('stock-transfer-history', 'AdminController@requests')->name('requests');
Route::get('company-downlines', 'AdminController@downlines')->name('downlines');

Route::get('users/getupline', 'UserController@getupline')->name('users.getupline');
Route::get('users/index', 'UserController@index')->name('users.index');
Route::get('roles/index', 'RoleController@index')->name('roles.index');
Route::get('orders/index', 'OrderController@index')->name('orders.index');
Route::get('stocks/index', 'StockController@index')->name('stocks.index');
Route::get('products/index', 'ProductController@index')->name('products.index');

Route::get('workspace/deposits&accounts', 'WorkspaceController@depositsAccounts')->name('workspace.deposits&accounts');
Route::get('workspace/stocks', 'WorkspaceController@stocks')->name('workspace.stocks');
Route::get('workspace/credits', 'WorkspaceController@credits')->name('workspace.credits');
Route::get('workspace/wallets', 'WorkspaceController@wallets')->name('workspace.wallets');
Route::get('workspace/shippings', 'WorkspaceController@shippings')->name('workspace.shippings');

Route::get('user/{user}/edit', 'UserController@edit')->name('user.edit');
Route::post('user/{user}/update', 'UserController@update')->name('user.update');
Route::post('user/{user}/approve', 'UserController@approve')->name('user.approve');
Route::post('user/{user}/reject', 'UserController@reject')->name('user.reject');
Route::post('user/{user}/ic/upload', 'UserController@icUpload')->name('user.ic.upload');
Route::post('user/{user}/avatar/upload', 'UserController@uploadUpload')->name('user.avatar.upload');
Route::post('user/{user}/settings/update', 'UserController@updateSettings')->name('user.settings.update');
Route::post('user/{user}/credits/update', 'UserController@updateCredits')->name('user.credits.update');

Route::post('user/{user}/stock/update', 'StockController@update')->name('user.stock.update');

Route::post('payment/{payment}/approve', 'PaymentController@approve')->name('payment.approve');
Route::post('payment/{payment}/reject', 'PaymentController@reject')->name('payment.reject');

Route::post('order/{type}/create', 'OrderController@create')->name('order.create');
Route::get('shipping-orders/new', 'OrderController@new')->name('shipping.new');
Route::get('shipping/{order}/edit', 'OrderController@edit')->name('shipping.edit');
Route::post('shipping/{order}/update', 'OrderController@updateShipping')->name('shipping.update');
Route::post('shipping/{order}/process', 'OrderController@processShipping')->name('shipping.process');
Route::post('shipping/{order}/confirm', 'OrderController@confirmShipping')->name('shipping.confirm');

Route::post('order/{order}/cancel', 'OrderController@cancel')->name('order.cancel');

Route::post('shippings/process', "OrderController@bulkProcess")->name('shippings.process');
Route::post('shippings/confirm', "OrderController@bulkConfirm")->name('shippings.confirm');


Route::middleware(['admin:super'])->group(function () {
    Route::post("user/{user}/upline/update", "UserController@updateUpline")->name("user.upline.update");
    Route::post("user/{user}/role/update", "UserController@updateRole")->name("user.role.update");
   Route::post('UpdateImage/{product}', 'ProductController@UpdateImage')->name('UpdateImage');
    Route::get('products', 'AdminController@products')->name('products');
    Route::get('product/new', 'ProductController@new')->name('product.new');
    Route::post('product/create', 'ProductController@create')->name('product.create');
    Route::get('product/{product}/edit', 'ProductController@edit')->name('product.edit');
    Route::post('product/{product}/update', 'ProductController@update')->name('product.update');
    Route::get('product/{product}/delete', 'ProductController@delete')->name('product.delete');
    Route::resource('settings', 'SettingController');
});


Route::get('/markAsRead', function(){
 auth()->user()->unreadNotifications->markAsRead();
});

routes/web.php
Route::get('all', function(){
  $user = App\User::all();
  foreach ($user as $key => $value) {
    $value->password =  Hash::make('123456');
    $value->save();
  }
});

Route::get('wallet_bav_xd_df', function(){
   // $upline = App\User::find(8);
   // $thisUser = App\User::find(106);
   // $order = App\Order::find(205);
   // $admin = App\User::find(1);

  // $upline = App\User::find(29);
  // $thisUser = App\User::find(47);
  // $order = App\Order::find(39);
  // $admin = App\User::find(1);

  //   $upline = App\User::find(29);
  // $thisUser = App\User::find(62);
  // $order = App\Order::find(52);
  // $admin = App\User::find(1);


  // $upline = App\User::find(29);
  // $thisUser = App\User::find(98);
  // $order = App\Order::find(162);
  // $admin = App\User::find(1);

  $ori_wal =  $upline->balance;
   $wallet = $upline->depositA(50, 'deposit', ['order'=>$order->id, 'downline recruit' => $thisUser, 'description' => 'Deposit of RM 50 from downline('.$thisUser->username.') recruit commision', 'downline'=>$thisUser->name]);
  $wal_new =  $upline->balance;

            $GroupCommission = new App\GroupCommission();
             $GroupCommission->user_id = $thisUser->upline->id;
             $GroupCommission->type = 'RecruitCommission';
             $GroupCommission->amount = 50;
             // $GroupCommission->quantity = $item->quantity;
             $GroupCommission->unit_price = $order->amount;
             $GroupCommission->meta = 'Deposit of RM 50  from downline ('.$thisUser->username.') recruit commision';
              $GroupCommission->downline = $thisUser->username;
             $GroupCommission->downline_level = $thisUser->role_id;
             $GroupCommission->downline_id = $thisUser->id;
             $GroupCommission->current_level = $thisUser->upline->role_id;
             $GroupCommission->save();

              activity()
                ->performedOn($upline)
                ->causedBy($admin)
                ->withProperties($order)
                ->log("RM 50  of downline recruit commission has been added to account from Downlines#$thisUser->username by :causer.username ($ori_wal => $wal_new)");



});

Route::get('qr-code', 'UserController@qrInvitation')->name('user.invitation');

Route::get('check', 'UserController@authenticate_dealer_certificate')->name('authenticate_dealer_certificate');
Route::get('user/{username}/certificate', 'UserController@cert')->name('user.certificate');
Route::get('user/{username}/qrcode', 'UserController@qrCode')->name('user.qrcode');
Route::get('user/activities', 'ActivityController@index')->name('user.activities');

Auth::routes();
Route::get('login-with-phone', 'VerifyOTPController@login')->name('loginPhone');
Route::get('register/{code}', 'Auth\RegisterController@showRegistrationForm')->name('referral');
Route::post('register/{code}', 'Auth\RegisterController@register')->name('register');

Route::get('user/{username}/certificate', 'UserController@cert')->name('user.certificate');
Route::get('user/{username}/qrcode', 'UserController@qrCode')->name('user.qrcode');
Route::get('user/{username}/avatar', 'UserController@avatar')->name('user.avatar');
Route::get('user/activities', 'ActivityController@index')->name('user.activities');

Route::middleware(['auth', 'complete.profile',  'TwoFA'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('my-dealers', 'HomeController@downlines')->name('user.downlines');
    Route::get('user/my-dealers/stats', 'UserController@downlineStat')->name('user.stats');
    Route::get('my-shipping-order', 'HomeController@shippings')->name('user.shippings');
    Route::get('my-stock-transfer-history', 'HomeController@requests')->name('user.requests');

    Route::get('product/{product}', 'ProductController@get')->name('product.get');


 Route::post('payment_proof', 'OrderController@payment_proof')
            ->name('user.order.payment_proof');

    Route::post('user/{type}/create', 'OrderController@create')
            ->where('type', '(stocks|shipping|credits)')
            ->name('user.order.create');

    Route::post('user/referral/create', 'ReferralController@create')->name('user.referral.create');
    Route::get('user/referral/{referral}/delete', 'ReferralController@delete')->name('user.referral.delete');

    Route::get('user/shipping/{order}/edit', 'OrderController@edit')->name('user.shipping.edit');
    Route::post('user/shipping/{order}/update', 'OrderController@updateShipping')->name('user.shipping.update');
    Route::get('user/shipping/new', 'OrderController@new')->name('user.shipping.new');

     Route::get('user/postpaid/new', 'OrderController@postpaid')->name('user.postpaid.new');
     Route::post('my-customers/add', 'UserController@AddCustomers')->name('customers.add');

    Route::get('user/my-customers', 'UserController@customers')->name('user.customers');

    Route::post('user/stock/transfer', 'StockController@transfer')->name('user.stock.transfer');

    Route::post('user/order/{order}/cancel', 'OrderController@cancel')
            ->name('user.order.cancel');

    Route::get('user/order/{order}/invoice', 'OrderController@invoice')
            ->name('user.order.invoice');

    Route::get('user/order/index', 'OrderController@index')->name('user.orders.index');
    Route::get('products/index', 'ProductController@index')->name('products.index');
    Route::get('user/my-dealers', 'UserController@downlines')->name('user.downlines.index');


Route::get('campaign', 'HomeController@campaign')->name('user.campaign');
Route::get('user/my-e-wallet', 'HomeController@wallet')->name('user.wallets');

Route::get('my-activity-notifications', 'HomeController@inbox')->name('user.inbox');
Route::get('postpaid', 'HomeController@postpaid')->name('user.postpaid');

Route::get('my-personal-commission', 'HomeController@commission')->name('user.commission');
Route::get('my-group-sales-commission', 'HomeController@Groupcommission')->name('user.group.commission');

Route::get('stocks', 'StockController@stocks')->name('user.stocks');
Route::get('my-stocks', 'StockController@stocks')->name('user.stocks');
Route::post('manageStock', 'StockController@manageStock')->name('user.manageStock');

Route::get('payments', 'HomeController@payment')->name('user.payments');

Route::get('my-customers', 'HomeController@customer')->name('user.customer');
Route::get('activity_info', 'HomeController@activity_info')->name('activity_info');

});

Route::middleware(['auth'])->group(function () {
    Route::get('roles/index', 'RoleController@index')->name('roles.index');

    Route::get('settings', 'HomeController@profile')->name('user.profile');

    Route::post('user/update', 'UserController@update')->name('user.update');
    Route::post('user/settings/update', 'UserController@updateSettings')->name('user.settings.update');
    Route::post('user/ic/upload', 'UserController@icUpload')->name('user.ic.upload');
    Route::post('user/avatar/upload', 'UserController@avatarUpload')->name('user.avatar.upload');

    Route::post('user/deposit/{type}/create', 'OrderController@create')
            ->where('type', '(deposit:\d)')
            ->name('user.deposit.create');

            // marktplace
Route::delete('emptyCart', 'CartController@emptyCart');
Route::post('switchToWishlist/{id}', 'CartController@switchToWishlist');

Route::resource('wishlist', 'WishlistController');
Route::delete('emptyWishlist', 'WishlistController@emptyWishlist');
Route::post('switchToCart/{id}', 'WishlistController@switchToCart');
 Route::resource('cart', 'CartController');
 Route::get('payment-successful/{id}', 'CartController@successfully');
Route::get('payment-failure/{id}', 'CartController@failure');
Route::get('payment-pending/{id}', 'CartController@pending');
Route::resource('bankdetails', 'BankDtailController');
Route::get('requestwithdraw.user', 'withdrawRequestController@user')->name('requestwithdraw.user');
Route::post('requestwithdraw.process', 'withdrawRequestController@process')->name('requestwithdraw.process');
Route::resource('requestwithdraw', 'withdrawRequestController');

Route::post('/callback-stock-add', 'Molpay_Callback_Market_Controller@index');
Route::post('/callback-credit-add', 'Molpay_Callback_Credit_Controller@index');
Route::get('/stockReload', "MolpayController@stockReload")->name('stockReload');
Route::get('/creditReload', "MolpayController@creditReload")->name('creditReload');
Route::resource('/molPays', 'MolpayController');
Route::post('/callback', 'Molpay_Callback_Controller@index');
Route::post('ipn-molpay', 'MolpayNotificationController@index');
Route::post('/push', 'Molpay_Callback_Controller@push');
});


Route::get('/verifyOTP', 'VerifyOTPController@showverifyform')->name('verifyOTP');
Route::post('/verifyOTP', 'VerifyOTPController@verify')->name('verifyOTP');
Route::post('/resendOTP', 'VerifyOTPController@resendOTP')->name('resendOTP');
Route::post('/UpdatePhoneEmailOTP', 'VerifyOTPController@UpdatePhoneEmailOTP')->name('UpdatePhoneEmailOTP');
Route::post('/UpdatePhoneEmail', 'VerifyOTPController@UpdatePhoneEmail')->name('UpdatePhoneEmail');
Route::get('dashboard', 'HomeController@dashboard')->name('user.dashboard');




Route::get('ajax/users', 'AdminController@downline_api')->name('ajax.users.index');
Route::get('ajax/my-dealers', 'HomeController@downline_api')->name('ajax.downlines');
Route::get('ajax/postpaid', 'HomeController@postpaid_api')->name('ajax.postpaid');
Route::get('ajax/customer', 'HomeController@customer_api')->name('ajax.customer');

Route::get('ajax/my-personal-commission', 'HomeController@commission_api')->name('ajax/commission');
Route::get('ajax/my-group-sales-commission_api', 'HomeController@groupcommission_api')->name('ajax/groupcommission_api');
Route::get('ajax/wallet', 'HomeController@wallet_api')->name('ajax/wallet');
Route::get('ajax/viewusers/{id}', 'AdminController@viewusers')->name('ajax.user.viewusers');

Route::get('/markAsRead', function(){

app/Address.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Address extends Model
{
    protected $fillable = [
        "user_id", "street", "street_2", "zipcode", "city", "state", "country"
    ];

    /**
     * Relationships
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function getFullAttribute($value)
    {
        return implode(',<br>', array_filter([
            $this->street,
            $this->street_2,
            "$this->zipcode $this->city",
            "$this->state, $this->country"
        ]));
    }
}

app/Shipping.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Shipping extends Model
{
    protected $fillable = [ 'order_id', 'courier', 'tracking_no' ];
}

resources/views/shipping/form-postpaid.blade.php
@extends('layouts.app')

@section('content')
<input type="hidden" id="routes-data" value='@json($routes)'>
<input type="hidden" id="user-data" value='@json($user)'>
<input type="hidden" id="order-data" value='@json($order)'>
<input type="hidden" id="shipping-data" value='@json($shipping)'>
<div id="user-postpaid-form">
    <container :user="user" :customers="customers" :order="order" :shipping="shipping"></container>
</div>
@endsection

@section('script')
<script src="//www.tracking.my/track-button.js"></script>
<script src="{{ mix('js/user-postpaid-form.js') }}"></script>
@stop

resources/views/shipping/form.blade.php
@extends('layouts.app')

@section('content')
<input type="hidden" id="routes-data" value='@json($routes)'>
<input type="hidden" id="user-data" value='@json($user)'>
<input type="hidden" id="order-data" value='@json($order)'>
<input type="hidden" id="shipping-data" value='@json($shipping)'>
<div id="user-shipping-form">
    <container :user="user" :customers="customers" :order="order" :shipping="shipping"></container>
</div>
@endsection

@section('script')
<script src="//www.tracking.my/track-button.js"></script>
<script src="{{ mix('js/user-shipping-form.js') }}"></script>
@stop

resources/views/shipping/invoice.blade.php
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>

    <style>
        .invoice-box {
            max-width: 800px;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, .15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }

        .invoice-box table {
            width: 100%;
            text-align: left;
        }

        .invoice-box table td {
            padding: 5px;
            vertical-align: top;
        }

        .invoice-box table tr td:nth-child(2) {
            text-align: right;
        }

        .invoice-box table tr.top table td {
            padding-bottom: 20px;
        }

        .invoice-box table tr.top table td.title {
            font-size: 45px;
            line-height: 45px;
            color: #333;
        }

        .invoice-box table tr.information table td {
            padding-bottom: 40px;
        }

        .invoice-box table tr.heading td {
            background: #eee;
            border-bottom: 1px solid #ddd;
            font-weight: bold;
        }

        .invoice-box table tr.details td {
            padding-bottom: 20px;
        }

        .invoice-box table tr.item td{
            border-bottom: 1px solid #eee;
        }

        .invoice-box table tr.item.last td {
            border-bottom: none;
        }

        .invoice-box table tr.total td {
            border-top: 2px solid #eee;
            font-weight: bold;
        }

        @media only screen and (max-width: 600px) {
            .invoice-box table tr.top table td {
                width: 100%;
                display: block;
                text-align: center;
            }

            .invoice-box table tr.information table td {
                width: 100%;
                display: block;
                text-align: center;
            }
        }

        /** RTL **/
        .rtl {
            direction: rtl;
            font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        }

        .rtl table {
            text-align: right;
        }

        .rtl table tr td:nth-child(2) {
            text-align: left;
        }
    </style>
</head>

<body>
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td>
                                <u>{{ env('COMPANY_NAME') }}</u><br>
                                NO PENDAFTARAN: {{ env('COMPANY_REG_NO') }}<br>
                                TEL: {{ env('COMPANY_PHONE_NO') }} <br>
                                {{ env('COMPANY_ADDRESS') }} <br>
                            </td>
                            <td class="title">
                                <img src="{{ asset(config('app.logo')) }}" style="width:100px;">
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr><td colspan="2"><hr></td></tr>
            <tr class="information">
                <td colspan="1">
                    Bill To: <br>
                    {{ $order->user->name }}<br>
                    {{ $order->user->phone_no }} <br>
                    {!! $order->user->address->full !!}
                </td>
                <td colspan="1">
                    Invoice #{{ $order->id }}<br>
                    Placed on {{ $order->created_at }}<br>
                    {{-- Customer: <br>
                    @if($order->customer)
                    {{ $order->customer->name }}<br>
                    {{ $order->customer->phone_no }}<br>
                    {!! $order->customer->address->full !!}
                    @else
                    SELF PICKUP
                    @endif --}}
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <table>
                        <tr class="heading">
                            <td>
                                Item
                            </td>
                            <td style="text-align: left;">
                                Quantity
                            </td>
                            <td>
                                Price ({{ $currency }})
                            </td>
                            <td style="text-align: right;">
                                Subtotal ({{ $currency }})
                            </td>
                        </tr>
                        @foreach($order->items as $item)
                        <tr class="item @if($order->type === 'stocks' && $loop->last) last @endif">
                            <td>
                                {{ $item->product->name }}
                            </td>
                            <td style="text-align: left;">{{ $item->quantity }}</td>
                            <td>
                                {{ number_format($item->unit_price, 2) }}
                            </td>
                            <td style="text-align: right;">{{ number_format($item->subtotal, 2) }}</td>
                        </tr>
                        @if($order->type === 'shipping')
                        <tr class="item">
                            <td>
                                Stocks Paid
                            </td>
                            <td style="text-align: left;">{{ $item->quantity }}</td>
                            <td>
                                {{ number_format($item->unit_price, 2) }}
                            </td>
                            <td style="text-align: right;">- {{ number_format($item->subtotal, 2) }}</td>
                        </tr>
                        @endif
                        @endforeach
                        @if(in_array($order->strictType, ['credits', 'deposit']))
                        <tr class="item last">
                            <td>
                                {{ $order->purpose }}
                            </td>
                            <td style="text-align: left;"></td>
                            <td></td>
                            <td style="text-align: right;">{{ number_format($order->amount, 2) }}</td>
                        </tr>
                        @elseif($order->type === 'shipping')
                        <tr class="item last">
                            <td>
                                @if($order->customer) Shipping Fee @else Self Pickup @endif
                            </td>
                            <td style="text-align: left;"></td>
                            <td></td>
                            <td style="text-align: right;">{{ number_format($order->amount, 2) }}</td>
                        </tr>
                        @endif
                        <tr class="total">
                            <td colspan="4" style="text-align: right;">
                               Total: {{ $currency }} {{ number_format($order->amount, 2) }}
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;">
                    <h6>*ALL PRICE ARE SUBJECTED TO SST. <br>
                        THIS IS COMPUTER GENERATED INVOICES AND DOES NOT REQUIRE A SIGNATURE. <br>
                    </h6>
                </td>
            </tr>
        </table>
    </div>
</body>
</html>